default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: need_one_more_development

test:
  <<: *default
  database: need_one_more_test

production:
  <<: *default
  database: need_one_more_production
  username: need_one_more
  password: <%= ENV['NEED_ONE_MORE_DATABASE_PASSWORD'] %>
